"""Locks for the parts of the translation updater that run without an API key.

The updater's one job is to apply the English change to the Japanese page and
nothing else, and everything that enforces that lives on this side of the model
call: what counts as re-syncable, how the diff is isolated, how an edit is
applied, and how the marker is re-stamped. The model's output is prose, checked
by a human; these are the mechanics that decide what the human ends up reviewing.

They are tested separately because they are the parts a CI run cannot exercise
in the failure cases that matter — a two-match anchor, an unreachable blob, a
marker that vanished mid-edit — and a mechanism nobody has seen fail is a
mechanism nobody has seen work.
"""

import importlib.util
import json
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent


def _load(name: str, filename: str):
    """Import a hyphenated script by path — `scripts/` is not a package."""
    spec = importlib.util.spec_from_file_location(name, ROOT / "scripts" / filename)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


translate = _load("translate_i18n_drift", "translate-i18n-drift.py")


PAGE = """<!-- i18n-source: docs/x.md@blob:{sha} -->

# タイトル

## 取得 {{ #retrieval }}

3 つの retriever が融合ステップに入力を与えます。

## 分離軸 {{ #isolation-axes }}

行は 3 つの軸で分離されます。
"""

OLD_SHA = "a" * 40
NEW_SHA = "b" * 40


# --------------------------------------------------------------------------------------
# An edit is applied only on an exact single match.
#
# The 0-match case is the obvious one. The 2-match case is the one that would ship: a
# short anchor appearing twice rewrites whichever paragraph came first, and every guard
# this repository runs stays green — the file is still valid Markdown, still carries its
# marker, still translates the right page. Nothing downstream can tell the difference
# between "the right paragraph changed" and "a paragraph changed", so the check has to
# happen here or not at all.
# --------------------------------------------------------------------------------------


def test_an_edit_matching_twice_is_refused_rather_than_guessed():
    page = "同じ文。\n\n別の段落。\n\n同じ文。\n"
    with pytest.raises(RuntimeError, match="2 times"):
        translate.apply_edits(page, [{"search": "同じ文。", "replace": "変更後。", "why": "x"}], "p")


def test_an_edit_matching_nothing_is_refused():
    with pytest.raises(RuntimeError, match="0 times"):
        translate.apply_edits("本文。\n", [{"search": "無い文", "replace": "y", "why": "x"}], "p")


def test_edits_apply_in_order_and_leave_everything_else_byte_identical():
    page = PAGE.format(sha=OLD_SHA)
    updated = translate.apply_edits(
        page,
        [{"search": "3 つの retriever が融合ステップに入力を与えます。",
          "replace": "3 つの retriever が融合ステップに入力を与えます (keyword は 4 本目ではありません)。",
          "why": "the English gained a parenthetical"}],
        "docs/x.ja.md",
    )
    assert "keyword は 4 本目ではありません" in updated
    # The untouched half is untouched — the property the whole design exists for.
    assert updated.split("## 分離軸")[1] == page.split("## 分離軸")[1]
    assert "{ #retrieval }" in updated, "an explicit heading id was lost"


# --------------------------------------------------------------------------------------
# The marker is re-stamped by this script, never by the model.
#
# A stamp written from the model's output would be a translation of a hash: the one field
# whose whole purpose is to say *which English content this page matches* would be
# generated by the same pass that might have got the content wrong, and a wrong-but-plausible
# sha reads as current to every checker. So the model is told not to touch it, and this
# fails loudly if the edits removed it anyway.
# --------------------------------------------------------------------------------------


def test_the_marker_is_restamped_to_the_content_that_was_translated():
    updated = translate.restamp(PAGE.format(sha=OLD_SHA), "docs/x.md", NEW_SHA, "docs/x.ja.md")
    assert f"docs/x.md@blob:{NEW_SHA}" in updated
    assert OLD_SHA not in updated


def test_a_marker_lost_during_editing_fails_instead_of_being_re_added():
    with pytest.raises(RuntimeError, match="marker went missing"):
        translate.restamp("# タイトル\n\n本文。\n", "docs/x.md", NEW_SHA, "docs/x.ja.md")


# --------------------------------------------------------------------------------------
# The diff is the unit of work — the page is not.
#
# A full re-translation is the easy implementation and the unreviewable one: the Japanese
# diff covers the page, and the sentence whose meaning moved is lost among the ones that
# were merely rephrased. This pins that only the changed region is ever handed over.
# --------------------------------------------------------------------------------------


def test_only_the_changed_region_reaches_the_model():
    before = "# T\n\n" + "\n\n".join(f"paragraph {i}" for i in range(60)) + "\n"
    after = before.replace("paragraph 30", "paragraph 30, now with a caveat")
    diff = translate.english_diff(before, after, "docs/x.md")
    assert "paragraph 30, now with a caveat" in diff
    assert "paragraph 5" not in diff, (
        "the diff carried unchanged prose; the point of diffing against the recorded blob "
        "is that the reviewer sees only what moved"
    )


def test_an_unreachable_blob_reports_rather_than_translating_the_whole_page():
    """A shallow clone loses the recorded English; the fallback would be a full re-translation."""
    assert translate.english_at("0" * 40) is None


# --------------------------------------------------------------------------------------
# Only a page that recorded what it translated can be re-synced.
#
# Missing / legacy / wrong-source markers all mean the same thing: nothing says which
# English text this page matches, so there is no change to isolate. Translating the whole
# page anyway would produce a diff nobody can review, which is how a fidelity error gets
# waved through.
# --------------------------------------------------------------------------------------


def test_the_checker_reports_what_a_re_sync_needs():
    """--json is the updater's input: the recorded blob is what makes a targeted edit possible."""
    proc = subprocess.run(
        ["python3", str(ROOT / "scripts" / "check-i18n-drift.py"), "--json"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, proc.stderr
    import json

    payload = json.loads(proc.stdout)
    assert "stale" in payload, (
        "check-i18n-drift.py --json stopped emitting a 'stale' key. That output is a "
        "contract, not a display format — translate-i18n-drift.py reads it, and scraping "
        "the ::error annotations instead is what this key exists to avoid."
    )
    for finding in payload["stale"]:
        assert set(finding) >= {"translation", "english", "reason", "translated_blob"}


# --------------------------------------------------------------------------------------
# A successful run and a usable answer are different things.
#
# Claude Code's structured-output contract says a run can end with subtype "success" and
# still carry no structured_output, and that this must be treated as a failure. Here that
# distinction is load-bearing in a way it usually is not: the value that would sail
# through is an EMPTY edit list, and an empty list is also the correct answer when the
# English change needs nothing on the Japanese side (a typo in a code sample). Conflating
# them re-stamps the marker on a page nobody translated — the drift check goes green over
# a translation that never happened, which is the exact failure the check exists to catch.
# --------------------------------------------------------------------------------------


def test_a_success_with_no_structured_output_is_a_failure_not_an_empty_edit_list():
    with pytest.raises(RuntimeError, match="no answer at all"):
        translate.extract_edits({"subtype": "success", "structured_output": None}, "docs/x.md")


def test_an_empty_edit_list_is_a_legitimate_answer():
    """'The English change needs no Japanese change' has to stay expressible."""
    assert translate.extract_edits(
        {"subtype": "success", "structured_output": {"edits": []}}, "docs/x.md"
    ) == []


def test_exhausted_retries_report_the_reason_rather_than_a_generic_failure():
    """The CLI re-prompts on a schema mismatch; this is what it says when it gives up."""
    with pytest.raises(RuntimeError, match="after the CLI's retries"):
        translate.extract_edits(
            {"subtype": "error_max_structured_output_retries", "result": "..."}, "docs/x.md"
        )


def test_any_other_terminal_subtype_names_itself():
    with pytest.raises(RuntimeError, match="error_during_execution"):
        translate.extract_edits({"subtype": "error_during_execution"}, "docs/x.md")


# --------------------------------------------------------------------------------------
# What a non-zero exit tells the reader.
#
# Both of these arrived in real CI runs and neither could arrive in a unit test that only
# exercised the success path: the reason for the failure was on the wrong stream, and then
# inside a document that was being truncated. The cost of getting it wrong is not a wrong
# answer but a round trip — the run fails, the message says nothing, and the next attempt
# starts by reproducing the failure to find out what it was.
# --------------------------------------------------------------------------------------


def _cli_exits(monkeypatch, *, stdout: str, stderr: str, code: int = 1):
    def fake_run(*args, **kwargs):
        return subprocess.CompletedProcess(args=[], returncode=code, stdout=stdout, stderr=stderr)

    monkeypatch.setattr(translate.subprocess, "run", fake_run)


def test_a_failure_written_to_stdout_is_still_reported(monkeypatch):
    """The CLI put an auth failure on stdout and left stderr empty."""
    _cli_exits(monkeypatch, stdout="OAuth access token is invalid", stderr="")
    with pytest.raises(RuntimeError) as exc:
        translate.request_edits("m", "low", "diff", "ja", "docs/x.md")
    assert "OAuth access token is invalid" in str(exc.value)
    assert "(empty)" in str(exc.value)  # stderr, named rather than silently omitted


def test_a_failed_run_reports_the_reason_inside_its_result_document(monkeypatch):
    """A failed run comes back as an ordinary result JSON, so the reason is a field."""
    _cli_exits(
        monkeypatch,
        stdout=json.dumps(
            {
                # Ahead of the reason on purpose: the first CI failure was read
                # off a raw slice of this document, and the slice ended before
                # the fields that said why.
                "session_id": "s" * 900,
                "subtype": "error_during_execution",
                "terminal_reason": "api_error",
                "api_error_status": 401,
                "result": "OAuth access token is invalid",
            }
        ),
        stderr="",
    )
    with pytest.raises(RuntimeError) as exc:
        translate.request_edits("m", "low", "diff", "ja", "docs/x.md")
    message = str(exc.value)
    assert "terminal_reason=api_error" in message
    assert "api_error_status=401" in message
    assert "OAuth access token is invalid" in message


# --------------------------------------------------------------------------------------
# A finding the updater cannot see is a finding that does not exist.
#
# The checker reports twice — once for a human (annotations, exit code) and once for a
# program (--json). Those two consumers are what makes a half-recorded finding dangerous:
# the run goes red, so a human eventually looks, while the updater reads an empty work
# list and reports nothing to fix. That is worse than a plain failure, because the job
# that is supposed to explain the red is the one saying everything is fine.
# --------------------------------------------------------------------------------------


def _tree(tmp_path: Path, pages: dict[str, str]) -> Path:
    """A minimal checkout: the real checker, and only the docs handed to it.

    Run against a copy rather than this repository's own docs/ because the case
    under test is a page that must not exist here — an orphan translation is
    exactly what the CI gate blocks.
    """
    (tmp_path / "scripts").mkdir()
    (tmp_path / "scripts" / "check-i18n-drift.py").write_bytes(
        (ROOT / "scripts" / "check-i18n-drift.py").read_bytes()
    )
    (tmp_path / "docs").mkdir()
    for name, body in pages.items():
        (tmp_path / "docs" / name).write_text(body)
    return tmp_path


def _check(tree: Path, *flags: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["python3", str(tree / "scripts" / "check-i18n-drift.py"), *flags],
        cwd=tree,
        capture_output=True,
        text=True,
    )


def test_a_translation_whose_english_source_is_gone_reaches_the_machine_output(tmp_path):
    """The exit code and --json used to disagree: red run, empty work list."""
    tree = _tree(tmp_path, {"gone.ja.md": f"<!-- i18n-source: docs/gone.md@blob:{OLD_SHA} -->\n\n# 孤児\n"})

    proc = _check(tree, "--json", "--strict")
    assert proc.returncode == 1, "an orphan translation is still a blocking finding"

    payload = json.loads(proc.stdout)
    assert [f["reason"] for f in payload["stale"]] == ["missing_source"], (
        "the checker exited non-zero but told the updater there was nothing to do; "
        "a finding that only reaches the human output cannot be reported by the job "
        "that runs on it"
    )
    finding = payload["stale"][0]
    assert finding["translation"] == "docs/gone.ja.md"
    assert finding["english"] == "docs/gone.md"
    assert finding["current_blob"] is None, "there is no English file left to hash"


def test_the_orphan_page_is_told_what_to_do_about_its_missing_source():
    """Its cause is not a broken marker, so the marker advice would not work."""
    advice = translate.skip_advice(
        {"translation": "docs/gone.ja.md", "english": "docs/gone.md", "reason": "missing_source"}
    )
    assert "docs/gone.md" in advice and "does not exist" in advice
    assert "Fix the marker" not in advice, (
        "no marker edit brings back a deleted English page; the two ways out are "
        "deleting the translation or repointing it"
    )
    assert "Fix the marker" in translate.skip_advice(
        {"translation": "docs/x.ja.md", "english": "docs/x.md", "reason": "missing_marker"}
    ), "the marker cases keep the advice that does work for them"


# --------------------------------------------------------------------------------------
# Exit 1 means two different things, so the exit code cannot be the verdict.
#
# The checker returns 1 for "drift found" under --strict; Python returns 1 for an
# uncaught exception. Reading the code alone therefore turns a crashed checker into a
# clean run, and the empty stdout that follows arrives at json.loads as "" — raising a
# JSONDecodeError that names column 1 and nothing else, while the traceback saying why
# is still unread in stderr. These pin that the reason reaches the reader.
# --------------------------------------------------------------------------------------


def _checker_is(monkeypatch, tmp_path: Path, body: str):
    fake = tmp_path / "fake-checker.py"
    fake.write_text(body)
    monkeypatch.setattr(translate, "CHECKER", fake)


def test_a_crashed_checker_reports_its_own_stderr_not_a_json_decode_error(monkeypatch, tmp_path):
    _checker_is(
        monkeypatch,
        tmp_path,
        'import sys\nprint("docs/ is not a directory", file=sys.stderr)\n'
        'raise RuntimeError("checker exploded")\n',
    )
    with pytest.raises(SystemExit) as exc:
        translate.stale_pages()
    message = str(exc.value)
    assert "docs/ is not a directory" in message, (
        "the checker's own explanation was dropped; the caller was left with "
        "'Expecting value: line 1 column 1', which describes the empty string it "
        "was handed and not the failure that produced it"
    )
    assert "checker exploded" in message
    assert "check-i18n-drift.py" in message


def test_output_that_is_not_the_agreed_document_is_named_as_such(monkeypatch, tmp_path):
    """Exit 0 with the wrong shape is a contract break, not an empty work list."""
    _checker_is(monkeypatch, tmp_path, 'import json,sys; json.dump({"findings": []}, sys.stdout)\n')
    with pytest.raises(SystemExit) as exc:
        translate.stale_pages()
    assert "stale" in str(exc.value), "name the key that was missing"
    assert "findings" in str(exc.value), "show what arrived instead"


def test_a_working_checker_still_parses(monkeypatch, tmp_path):
    """The guards must not swallow the ordinary answer — including 'nothing stale'."""
    _checker_is(monkeypatch, tmp_path, 'import json,sys; json.dump({"stale": []}, sys.stdout)\n')
    assert translate.stale_pages() == []
